set shell := ["bash", "-uc"]
name := shell("yq .name src/antora.yml | tr '-' '_'")
site_title := shell("yq .title src/antora.yml")
has_nav := shell("yq '.nav // [] | any' src/antora.yml")

_default:
    @just --list --unsorted --justfile {{justfile()}}

# Build and serve website locally
[group("development")]
preview: build serve

# Build all versions as in CI/CD pipeline and serve website locally
[group("development")]
preview-production: && serve
    #!/bin/bash
    CI=true just build

# Build website
[group("development")]
build: 
    @echo "Generating site using Antora…"
    @if [ $CI == "true"  ]; then \
        jinja \
            -D site_url https://modellen.netbeheernederland.nl/{{name}} \
            -D site_title "{{site_title}}" \
            -D has_nav {{has_nav}} \
            /opt/build/antora/antora-playbook.yml.jinja > /tmp/antora-playbook.yml; \
        antora --fetch /tmp/antora-playbook.yml; \
    else \
        jinja \
            -D site_url http://localhost:8080 \
            -D site_title "{{site_title}}" \
            -D has_nav {{has_nav}} \
            /opt/build/antora/antora-playbook.local.yml.jinja > /tmp/antora-playbook.local.yml; \
        antora --fetch /tmp/antora-playbook.local.yml; \
    fi
    @echo
    @echo -e "Generated documentation files at: output/docs/html"
    @echo

# Serve the built website locally
[group("development")]
serve:
    @echo -e "Serving website from output/docs/html…"
    @echo
    http-serve output/docs/html
